postgresql:
  enabled: false

externalDatabase:
  port: 5432
  user: keycloak
  database: bitnami_keycloak
  existingSecretPasswordKey: "password"
  existingSecret: "keycloak.keycloak-postgres-db.credentials.postgresql.acid.zalan.do"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1024Mi